### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by williamnolan** [axuno/MailMergeLib#1]
What is the status of this library?  I've spent an entire day trying to get it to compile and run on VS 2015, to no avail.  Should I be using the codeproject version?  :)

Btw, I downloaded the zip yesterday, rather than using the GitHub protocol (I'm new to GitHub).  Maybe the zip isn't synchronized?

**Comment by axunonb** [comment]
If it didn't compile, what was the reason? E.g. did you have missing references (which would be a hint for missing NuGet packages)?
Did the assamblies in the zip file work for you?
I updated to AngleSharp 0.9.8 before, so maybe you will give it another try.

**Comment by williamnolan** [comment]
Yeah, missing references to the MailMergLib.   No matter how I referenced it, so that the IDE showed it as resolved, it would still throw the missing reference error upon compile.

Any specific configuration or build properties that I should be setting?

Not sure what you mean by "missing NuGet packages"...  Perhaps I have to get GitHub working.  Should I be fine with the zip alone?

**Comment by williamnolan** [comment]
Also, there is an unresolved reference to BouncyCastle.crypto, which isn't included in the download.  Does this matter?

**Comment by axunonb** [comment]
BouncyCastle.Crypto.dll was indeed missing in the zip file. I just added it now.
NuGet packages should automatically be loaded by VS2015 upon compile. There's a menu "manage NuGet packages" in the VS2015 menu. You'll find the downloaded assemblies in a folder "packages". No specific configuration, should work out of the box.

**Comment by axunonb** [comment]
Ah, now I see: the automatic NuGet packages download goes one level too deep. Gotta fix that. In the meantime just move the packages folder one level up and VS2015 will find the referenced assemblies.

**Comment by axunonb** [comment]
Solved with the latest repo update.

**Comment by williamnolan** [comment]
Thanks; got it working.  I had actually just accidentally happened across that solution as well by poking around with the NuGet menus.  I just updated from 2013 to 2015, and I haven't really become too familiar with NuGet or GitHub - still stuck in my old ways!  LOL
