### ISSUE TITLE
Error: 'MailMergeMessage' does not contain a definition of 'Deserialize'

### ISSUE THREAD

**Issue by ReckeDJ** [axuno/MailMergeLib#10]
Hi there!

Your lib looks good, it has almost all the features that I would like to see. One of the functions I would like to use is the 'templating' but only to store the plain and html code in xml files. I like the idea that e-mail layouts are separated from the controllers.

But, when I tried your example code in the Wiki about deserialisation, the error as mentioned in the title came up. Currently I have NuGet version 5.2.0.1 installed, maybe NuGet needs a new version to include the latest features?

Thanks in advance!
Joey

**Comment by axunonb** [comment]
Hi Joey!
The repo on GitHub and its documentation is already prepared for v5.3 which is going to be released during the next few days and also published on NuGet. You're welcome to download and give it a try.
Norbert

**Comment by ReckeDJ** [comment]
Thanks for the quick reply Norbert! Great work, as soon as the package is ready for NuGet, I will implement the (de)serialisation functions. Thanks again!

**Comment by axunonb** [comment]
Release v5.3.0 is now available: https://github.com/axuno/MailMergeLib/releases/tag/v5.3.0.0
