### ISSUE TITLE
Performance benchmarks?

### ISSUE THREAD

**Issue by hades200082** [axuno/MailMergeLib#11]
I have a client that has registered members and sends newsletters on a regular basis.  These can be sent to anywhere between 1,000 and 100,000 subscribers depending on the segmentation.

Can you provide any benchmarks for how fast MailMergeLib could get through, for example, 50,000 emails?

They would all be the same content with the exception of a few personalizations such as recipient name, email, etc.

The SMTP server would be a well-known service such as SendGrid or MailGun.

Thanks

**Comment by axunonb** [comment]
No, there are no reliable benchmarks, Concerning speed my guess is, that the data exchange with the mail service is the most crucial factor. Timing on my local machine, just to give you an idea:

* 100,000 messages
* 1 kB plain text including placeholders, mail-to address including placeholders
* 10 tasks for SmtpClients
* 1 local SMTP mail server

**Time: 29.4 seconds**
But give it your own try, it's simple. Would be curious about the outcome.
