### ISSUE TITLE
Events OnMessageFailure and OnSendFailure don't always fire as/when expected

### ISSUE THREAD

**Issue by axunonb** [axuno/MailMergeLib#15]
Example, where ```OnMessageFailure``` will not fire before ```MailMergeSender``` throws an exception.
```csharp
var mmm = new MailMergeMessage("Subject {dummy}", "Plain", "Html");
mmm.SmartFormatter.Settings.FormatErrorAction = ErrorAction.ThrowError;
mmm.SmartFormatter.Settings.ParseErrorAction = ErrorAction.ThrowError;
[...]
var mms = new MailMergeSender();
mms.OnMessageFailure += (sender, eventArgs) => { Console.WriteLine($"{eventArgs.Error.ToString()}"); };
try
{
    mms.Send(mmm, new Dictionary<string, string>() {{"key", "value"}});
}
catch (Exception e)
{
    Console.WriteLine(e);
}
```

At the same time, ```MailMergeSender``` should not throw a ```MailMergeMessageException``` for any parse or format errors, unless ```ErrorAction.ThrowError``` is set for ```FormatErrorAction``` or ```ParseErrorAction```. See also issue https://github.com/axuno/MailMergeLib/issues/14

**Comment by hades200082** [comment]
Even if `ErrorAction.ThrowError` is set, should MailMergeLib not report it through one of the error handlers instead of throwing an exception its self?

**Comment by axunonb** [comment]
Yes, this exactly is the idea:
1. Handling inside MailMergeLib will be independent from error settings in SmartFormat
2. Propagate failure events more properly
3. I think it is important to note, that as long as a message has formatting or parsing issues coming from SmartFormat, it must never move to MailMergeSender, but throw a MailMergeMessageException. This shall include SmartFormat issues (i.e. inner exceptions if SmartFormat throws errors).
Do you agree on that?

**Comment by axunonb** [comment]
Closed with commit https://github.com/axuno/MailMergeLib/commit/1eb3e2fb10c5392a6cf2b3f8c7e243e655b3f425

**Comment by axunonb** [comment]
@hades200082: Did this release work for you?
