### ISSUE TITLE
JSON as a datasource

### ISSUE THREAD

**Issue by geoffrussel** [axuno/MailMergeLib#17]
Has anyone been able to get this library working using a WebApi Controller that accepts a dynamic object/payload and passes it on to MailMergeSender.Send? On my dto.Payload, I have tried accepting a dynamic, an ExpandoObject, an object, a Dictionary<string,string>, and additionally I have tried casting all of these to object and always produces the same error. The controller accepts the request just fine, and I can access and see the variables correctly when setting a breakpoint and using the immediate window.

It works just fine if I manually pass an object that I create in the code (ie: at compile time) such as:
`new { ProjectId = "123", ProjectName = "hi" }`

But with a dynamic object generated at runtime, none of the functionality seems to work. This may be a bug in SmartFormatter, since if I try to pass the same object to a basic Smart.Format call, it also does not work.

`var message = new MailMergeMessage() { Config = settings.MessageConfig };`
`message.Subject = "Subject - Project ID: {ProjectId}";`
`message.HtmlText = "Body - Project Name: {ProjectName}";`

`_sender.Send(message, emailRequestDto.Payload);`

_VariableException: Variable(s) for placeholder(s) not found: {ProjectId}, {ProjectName}_

I am building a micro service that accepts email requests using templates already sent to the service. The payload is completely dynamic and specific to each consumer and their template. Is it possible to use this library for this purpose?

**Comment by axunonb** [comment]
The example is not complete, so it's difficult to analyze in depth.
However, your ```emailRequestDto.Payload``` might be interpreted as an ```IEnumerable```, and a cast could resolve the problem:
```_sender.Send(message, (object) emailRequestDto.Payload);```
We tried the following which worked perfectly:
```Csharp
var payload = new {ProjectId = "123", ProjectName = "hi"};
var message = new MailMergeMessage();
message.Subject = "Subject - Project ID: {ProjectId}";
message.HtmlText = "Body - Project Name: {ProjectName}";
message.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.From, "joe@doe.com"));
message.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.To, "mary@doe.com"));
var mimeMessage = message.GetMimeMessage((object) payload);
```

**Comment by geoffrussel** [comment]
Sorry, let me provide the full code. What you pasted above works for me, because the payload is defined in the code. The issue only occurs when the payload is defined at runtime. I spun up a .NET 4.6.1 WebApi project and used the following code for the ValuesController:

```csharp
namespace WebApplication1.Controllers
{
    public class ValuesController : ApiController
    {
        // POST api/values
        public void Post([FromBody]EmailRequestDto emailRequestDto)
        {
           var settings = new Settings
            {
                MessageConfig =
                {

                },
                SenderConfig =
                {
                    SmtpClientConfig = new[]
                    {
                        new SmtpClientConfig()
                        {
                            Name = "Production",
                            MessageOutput = MessageOutput.SmtpServer,
                            SmtpHost = "xxxxx.xxxxxx.com",
                            SmtpPort = 25,
                            NetworkCredential = null,
                            MaxFailures = 2,
                            RetryDelayTime = 500,
                            DelayBetweenMessages = 100,
                            Timeout = 3000
                        }
                    },
                    MaxNumOfSmtpClients = 5
                }
            };
            var _sender = new MailMergeSender { Config = settings.SenderConfig };
            var message = new MailMergeMessage() { Config =settings.MessageConfig };
            message.Subject = "Subject - Project ID: {Project.Id}";
            message.PlainText = "";
            message.HtmlText = "Body - Project Name: {Project.Name}";

            message.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.From, "do-not-reply@xxxxxx.com"));
            message.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.To, emailRequestDto.To));
            if (emailRequestDto.Cc != null)
                message.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.CC, emailRequestDto.Cc));
            if (emailRequestDto.Bcc != null)
                message.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.Bcc, emailRequestDto.Bcc));

            _sender.OnMessageFailure += _sender_OnMessageFailure;
            _sender.OnSendFailure += _sender_OnSendFailure;
            var mimeMessage = message.GetMimeMessage((object)emailRequestDto.Payload);
            _sender.Send(message, (object) emailRequestDto.Payload);
        }

        private void _sender_OnMessageFailure(object sender, MailMessageFailureEventArgs e)
        {
            Console.WriteLine(e.Error.Message);
            throw new System.NotImplementedException();
        }

        private void _sender_OnSendFailure(object sender, MailSenderSendFailureEventArgs e)
        {
            Console.WriteLine(e.Error.Message);
            throw new System.NotImplementedException();
        }
    }

    public class EmailRequestDto
    {
        public Guid ApplicationId { get; set; }
        public Guid NotificationTemplateId { get; set; }
        public dynamic Payload { get; set; }
        public string To { get; set; }
        public string Cc { get; set; }
        public string Bcc { get; set; }
    }
}
```

Blows up at:

var mimeMessage = message.GetMimeMessage((object)emailRequestDto.Payload);

**Comment by axunonb** [comment]
Ah, now I hope I got you, thanks. The remaining question is, which value(s) will be assigned to the```Payload``` property. Can you cast the ```dynamic``` to a ```IDictionary<string, object>```?
From my understanding, there is no magic behind the scenes that will create your ```dynamic Payload``` when posting the model, instead of assigning it in your code. [This article](https://dejanstojanovic.net/aspnet/2017/september/posting-json-to-webapi-without-reference-to-a-model-in-c/) may point you into the right direction.

**Comment by geoffrussel** [comment]
Here is an example POST request to that endpoint. Should only take a few minutes to spin up a .NET 4.6.1 app with Web API to validate.

```json
{
  "ApplicationId": "6a1a9c12-6f58-358c-8205-9c6219befdae",
  "NotificationTemplateId": "1f8a12ae-c715-4ce5-85aa-0b939411e714",
  "Payload": {
  	"Project" : {
  		"Id": 123,
  		"Name": "Awesome Project"
  	}
  },
  "To": "some.email@123.com"
}
```

If you set a breakpoint, you can easily access the Payload.Project.Id property. The dynamic object becomes a JObject when the controller interprets the POST. I can cast it to a Dictionary of <string, object>, but then the same exact problem just gets pushed to the next level of the tree (can access Payload.Project, but not Payload.Project.Id). I think the issue here is that the underlying .NET string formatter being used does not support reflection to get properties of dynamic objects.

I have switched to NVelocity for templates, which does support being passed a dynamic object (see below). If there are no plans to support this in MailMergeLib, please feel free to close this issue. It's a great library and I will still use it for dispatching, just not for templates.

```csharp
Velocity.Init();
var velocityContext = new VelocityContext();
velocityContext.Put("payload", emailRequestDto.Payload);
var subjectString = new StringBuilder();
var bodyString = new StringBuilder();
Velocity.Evaluate(velocityContext, new StringWriter(subjectString), "SubjectTemplate", new StringReader("Subject - Project ID: $payload.Project.Id"));
Velocity.Evaluate(velocityContext, new StringWriter(bodyString), "BodyTemplate", new StringReader("Body - Project Name: $payload.Project.Name"));
message.HtmlText = bodyString.ToString();
message.Subject = subjectString.ToString();
```

**Comment by axunonb** [comment]
Hi Geoff
Actually I'm considering to support JSON out-of-the-box, just like it's the case with XML. especially because converting ```JObject```s to a ```Dictionary<string,object>``` is not too difficult:
```Csharp
public static class JsonConversionExtensions
{
    public static IDictionary<string, object> ToDictionary(this JObject json)
    {
        var propertyValuePairs = json.ToObject<Dictionary<string, object>>();
        ProcessJObjectProperties(propertyValuePairs);
        ProcessJArrayProperties(propertyValuePairs);
        return propertyValuePairs;
    }

    private static void ProcessJObjectProperties(IDictionary<string, object> propertyValuePairs)
    {
        var objectPropertyNames = (from property in propertyValuePairs
            let propertyName = property.Key
            let value = property.Value
            where value is JObject
            select propertyName).ToList();

        objectPropertyNames.ForEach(propertyName => propertyValuePairs[propertyName] = ToDictionary((JObject)propertyValuePairs[propertyName]));
    }

    private static void ProcessJArrayProperties(IDictionary<string, object> propertyValuePairs)
    {
        var arrayPropertyNames = (from property in propertyValuePairs
            let propertyName = property.Key
            let value = property.Value
            where value is JArray
            select propertyName).ToList();

        arrayPropertyNames.ForEach(propertyName => propertyValuePairs[propertyName] = ToArray((JArray)propertyValuePairs[propertyName]));
    }

    public static object[] ToArray(this JArray array)
    {
        return array.ToObject<object[]>().Select(ProcessArrayEntry).ToArray();
    }

    private static object ProcessArrayEntry(object value)
    {
        if (value is JObject o)
        {
            return ToDictionary(o);
        }
        if (value is JArray array)
        {
            return ToArray(array);
        }
        return value;
    }
}
```
Credits to [Uli`s](https://stackoverflow.com/users/1764844/uli) post on SO.

At the same time, follwing the design of ```SmartFormat.NET``` support for JSON should go into a "JsonSource" extension. Given the simplicity of the above extension method, what would you vote for?

Using above extension methods, the solution in your case looks like that:
```Csharp
string json = @"{
  ""ApplicationId"": ""6a1a9c12-6f58-358c-8205-9c6219befdae"",
  ""NotificationTemplateId"": ""1f8a12ae-c715-4ce5-85aa-0b939411e714"",
  ""Payload"": {
  	""Project"" : {
  		""Id"": 123,
  		""Name"": ""Awesome Project""
  	}
  },
  ""To"": ""some.email@123.com""
}";
```
In your Asp.Net App the controller will get this argument:
```Csharp
var argToController = JObject.Parse(json);
```

**Now the new extension will convert the ```JObject``` recursively:**
```Csharp
var payload = argToController.ToDictionary();
```
The rest is as usual:
```Csharp
var message = new MailMergeMessage();
message.Subject = "Subject - Project ID: {Payload.Project.Id}";
message.HtmlText = "Body - Project Name: {Payload.Project.Name}";
message.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.From, "joe@doe.com"));
message.MailMergeAddresses.Add(new MailMergeAddress(MailAddressType.To, "{To}"));
// no exception this time
var mimeMessage = message.GetMimeMessage(payload);
```

**Comment by geoffrussel** [comment]
Great! I think that support for dynamic JSON objects is a very valuable feature to have in a template engine. I always encourage developers to use strictly-typed classes, however sometimes it's necessary or valuable to use loosely-typed objects (especially when creating a generic micro service such as logging/email/eventing etc where the micro service doesn't really care about what type of data it is).

If you add this functionality, I would be happy to help test it and add examples to the documentation!

**Comment by axunonb** [comment]
@geoffrussel There is an [update to SmartFormat.NET](https://github.com/scottrippey/SmartFormat.NET/commit/810740946060a1353f6cc8b69e1c5d32dbd0f73d) which fully supports JSON. Performance is similar to ```DictionarySource```, i.e. quite okay. There are also some initial test cases. Would you like to test and contribute on SmartFormat.NET? Finally the very same code would go into MailMergeLib.
