### ISSUE TITLE
Unit test "Indentify_Windows_Platform" fails on Linux

### ISSUE THREAD

**Issue by axunonb** [axuno/MailMergeLib#21]
_Originally posted by @thegruffalo in https://github.com/axuno/MailMergeLib/issues/19#issuecomment-538500319_

**Comment by axunonb** [comment]
> Did you mean to make the Indentify_Windows_Platform test conditional - fails on linux.

Actually the test should work also without ```ExcludePlatform```. The intention is to in include the new ```Platform``` class in unit tests.

**Comment by axunonb** [comment]
@thegruffalo Could you elaborate what exactly fails with the test, please?

**Comment by thegruffalo** [comment]
Here is the test output:

---- Test Execution Summary -----

MailMergeLib.Tests.Platform.Indentify_Windows_Platform:
    Outcome: Failed
    Error Message:
    MailMergeLib.UnsupportedPlatformException : Unknown
    Stack Trace:
       at MailMergeLib.Platform.DeterminePlatform() in /home/thill/tdev/MMLO/MailMergeLib/MailMergeLib/Platform.cs:line 65
   at MailMergeLib.Tests.Platform.Indentify_Windows_Platform() in /home/thill/tdev/MMLO/MailMergeLib/MailMergeLib.Tests/Platform.cs:line 24
    
Total tests: 1. Passed: 0. Failed: 1. Skipped: 0

As an alternative, maybe, something like this would be easier to implement https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.isosplatform?view=netcore-2.2

**Comment by axunonb** [comment]
With commit https://github.com/axuno/MailMergeLib/commit/1b08f3690be530f5dd50f96129ac74b95c3d7265 we're using ```System.Runtime.InteropServices.OSPlatform``` to detect the platform. Does the test pass now on Linux?

**Comment by axunonb** [comment]
Tests for commit https://github.com/axuno/MailMergeLib/commit/1b08f3690be530f5dd50f96129ac74b95c3d7265 complete successfully on Ubuntu 18.04 LTS and Windows.
