### ISSUE TITLE
Test CancelSendOperationWithDelay fails on Linux

### ISSUE THREAD

**Issue by axunonb** [axuno/MailMergeLib#22]
_Originally posted by @thegruffalo in https://github.com/axuno/MailMergeLib/issues/19#issuecomment-538500319_

**Comment by axunonb** [comment]
@thegruffalo Looks like I need a Linux system. What setup are you using on your side?

**Comment by thegruffalo** [comment]
I use Ubuntu 19.04. 
The easiest thing to do would be to use a VM (VirtualBox or similar) with a desktop Ubuntu installation - https://ubuntu.com/download/desktop
Then install dotnetcore sdk https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current
Then install vscode https://code.visualstudio.com/download (select the .deb package)

**Comment by axunonb** [comment]
Thanks for your hint. I've installed Ubuntu and use it with WSL now. Pretty good experience.

**Comment by axunonb** [comment]
This had 2 reasons:
1. The test assumed, the task can be cancelled even for the first message before it is sent. Given the tiny size of the test message, this is not reliable and depending on the SMTP connection and server. This was not well designed.
2. ```SmtpClientConfig.DelayBetweenMessages``` was not applied before sending the first message.

Resolved with commit https://github.com/axuno/MailMergeLib/commit/033b98450b843d60e598bc37da7023a6abd9188e
