### ISSUE TITLE
Not compatible with MailKit v3.0

### ISSUE THREAD

**Issue by Scantheus** [axuno/MailMergeLib#23]
After updating my nugets in an application that I've been using MailMergeLib for months without issue, it now gives me this exception error (see attached image).

Another application that uses MailMergeLib still works because I haven't updated nugets.

Both use lastest MailMergeLib v5.7.1 but the one that breaks uses MailKit v3.0 instead of MailKit v2.15.

It looks like MailKit 3.0 introduced a breaking change.

![image](https://user-images.githubusercontent.com/21069807/148586409-262ad5cc-bdcc-47ab-b512-b273de198637.png)

**Comment by Scantheus** [comment]
Looking through MailKit change history, the return value of the Send method was changed from void to string 8 months ago.
Mailkit v3.0 was release about a month ago.
MailMergeLib dependency in nuget accepts MailKit version 2.4 or higher.

**Comment by axunonb** [comment]
Thanks for the hint, gotta fix this.
Btw. MailMergeLib will get a major update after [SmartFormat v3.0](https://github.com/axuno/SmartFormat/blob/version/v3.0/CHANGES.md) will be released. I'm just working on that. Are you making use it's formatting capabilities?

**Comment by axunonb** [comment]
Fixed with [version 5.8.0](https://github.com/axuno/MailMergeLib/tree/v5.8.0.0)
