### ISSUE TITLE
Not compatible with SmartFormat v3.0

### ISSUE THREAD

**Issue by Scantheus** [axuno/MailMergeLib#25]
MailMergeLib v5.8
SmartFormat v3.0
Framework v4.8

MailMergeMessage mmm = new MailMergeMessage("Subject", "Message");

Gets exception "Method not found: 'Void.SmartFormat.SmartFormatter..ctor()'

![Screen-2022-05-12_13-38-36](https://user-images.githubusercontent.com/21069807/168146645-e7e090c0-a7d0-4fd3-8b49-35e0318a17a0.jpg)

**Comment by axunonb** [comment]
Correct, MailMergeLib v5.8 references SmartFormat v2.7.2

**Comment by Scantheus** [comment]
Then shouldn't nuget dependency be set to SmartFormat.NET = 2.7.2 instead of >= 2.7.2?

**Comment by Scantheus** [comment]
Ah, found the issue. Interesting. I think because my app is targeting NET 4.8, it doesn't take lowest version of dependencies since only NET v4.6.1 is in the MailMergeLib dependencies. I created a blank solution targeting Net 4.6.1 and correct dll versions are downloaded.

**Comment by axunonb** [comment]
@Scantheus Today we released a new maintenance version of *MailMergeLib* (`v5.8.2`), which is available on NuGet. We included an explicit range of compatible versions for dependencies. Does this for for you, too?

**Comment by Scantheus** [comment]
I don't see .NETFramework.Version=v4.8 in the Dependencies.

**Comment by Scantheus** [comment]
Tested (and it's a mess to revert back oof). You need NETFramework,Version=v4.8 with the same dependencies you have for v4.6.1. It appears if a framework is not explicitly defined, it will automatically take the latest version of the dependent packages. In this case, it pulls SmartFormat.NET v3.

**Comment by axunonb** [comment]
Couldn't find anything about this behavior [here](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning) and anywhere else. Thanks again for pointing this out.

**Comment by axunonb** [comment]
Resolved with #38
