### ISSUE TITLE
Error when trying to use base64 encoded image in html template

### ISSUE THREAD

**Issue by rsegerink** [axuno/MailMergeLib#3]
When I embed an image by base64 encoding in an html template, I get an System.IO.PathTooLongException. So it seems that the html parser still wants to resolve the image src value to a file system path, is there a setting to disable this?

**Comment by axunonb** [comment]
You mean embedding this way:
`<img alt="sample" src="data:image/png;base64,xyz" />`
Haven't verified yet, but I guess it doesn't work and I'd rate it as a bug (not too difficult to fix, though).

**Comment by rsegerink** [comment]
Yes.

**Comment by axunonb** [comment]
Bug should be removed with v5.2.0.0
