### ISSUE TITLE
Error wheny trying to use http image in html template

### ISSUE THREAD

**Issue by rsegerink** [axuno/MailMergeLib#4]
When I want to use an image by referencing it by http(s), I get an NotSupportedException error. It seems that it still wants to resolve an http:// image to a file:// image. 
Stacktrace: 

bij System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   bij MailMergeLib.Tools.MakeFullPath(String basename, String filename)
   bij MailMergeLib.HtmlBodyBuilder.ReplaceImgSrcByCid()
   bij MailMergeLib.HtmlBodyBuilder.GetBodyPart()
   bij MailMergeLib.MailMergeMessage.BuildTextMessagePart(Object dataIteam)
   bij MailMergeLib.MailMergeMessage.GetMimeMessage(Object dataItem)

**Comment by axunonb** [comment]
Bug should be removed with v5.2.0.0
