### ISSUE TITLE
HtmlBodyBuilder SearchAndReplaceVars breaks when script or style tags contain whitespace

### ISSUE THREAD

**Issue by pamenja** [axuno/MailMergeLib#48]
Hi,

MailMergeLib-5.12.3 
Framework version: net462

When I have css in the `<Head>` as `<style>` then the SearchAndReplaceVars in the HrmlBodyBuilder class does not work.

My Code:
```

var htmlBody = @"<!DOCTYPE html><html> <head><style type=""text/css"">body { font-size: 12px;}</style ></head>
  <body>hi {Verzender}, this is a test.</body></html>";

public class MyDataObject
{  
 public string Verzender { get; set; } = "Test User"
}

 _mailMergeMessage = new MailMergeMessage(mailContent.Subject, null, htmlBody);

_myDataObject= new MyDataObject;
_mailMergeSender.Send(_mailMergeMessage, _myDataObject);

HtmlBodyBuilder.cs line 45 breaks because of the css in the head:
var htmlFormatted = mailMergeMessage.SearchAndReplaceVars(mailMergeMessage.HtmlText, dataItem);
```

- What is the current result? htmlFormatted is mailMergeMessage.HtmlText
- What is the expected result? {Verzender} becomes Test User

- Did you find a workaround? yes
```

var parser = new HtmlParser();
_htmlDocument = parser.ParseDocument(mailMergeMessage.HtmlText);

if (_htmlDocument != null && _htmlDocument.Body != null)
{
  var body = _htmlDocument.Body.InnerHtml;
  var htmlFormatted = mailMergeMessage.SearchAndReplaceVars(body, dataItem);
  _htmlDocument.Body.InnerHtml = htmlFormatted;
}
```

Is there a version in which it worked? yes, before SmartFormat3

Hope this is clear? 

Paul

**Comment by axunonb** [comment]
Not sure what you mean by "HtmlBodyBuilder.cs line 45 breaks".
I just tested with the closing tag without the space `</style>` and it worked. Our parser is not as permissive as browsers.
Can you confirm?

**Comment by axunonb** [comment]
We added a corresponding hint to the [`SmartFormat` Wiki](https://github.com/axuno/SmartFormat/wiki/HTML-with-CSS-or-JavaScript)

**Comment by pamenja** [comment]
Thank you for the reply. And for the clarification!

I have adjusted the closing style-tag, after which it worked.

My conclusion: I should have read the wiki better.
