### ISSUE TITLE
System.IO.IOException when trying to delete a file that was used as an attachment

### ISSUE THREAD

**Issue by gary-palmer** [axuno/MailMergeLib#5]
Hi,

I seem to have trouble deleting attachments after sending an email.

After `.Send` I am calling `MailMergeMessage.GetMimeMessage` so that I can save the mime message to a directory of sent items.

I then try clear up some temp files (the attachments), but i get an exception that another process has the file in use.

I get the error when calling `MailMergeMessage.GetMimeMessage` regardless of whether I call `.WriteTo()`

I'm disposing of the sender, and setting the `MailMergeMessage` to null/nothing, any ideas?

thanks

**Comment by gary-palmer** [comment]
OK got it;

When sending a message, `MailMergeSender.SendMimeMessage` has some cleanup code;
`// Do some clean-up with the message
foreach (var mimeEntity in mimeMsg.Attachments)
{
  var att = mimeEntity as MimePart;
  att?.ContentObject.Stream.Dispose();
}`

Whereas the GetMimeMessage does not.  I have added the above to my code, but should this be added to `GetMimeMessage`?  or perhaps to the documentation?

**Comment by axunonb** [comment]
Yes, thanks for the hint, this makes perfect sense. Will be included in the next release.

**Comment by gary-palmer** [comment]
Great thanks.

Thanks for your work by the way...

**Comment by axunonb** [comment]
Just had a closer look and I wonder how mean that: ```GetMimeMessage``` is expected to return the complete message to send, including all required attachments, which may also include streams. If you dispose the streams in the ```MimeMessage``` to return they are gone before the caller can send the message. Could you post your code snippet?

**Comment by axunonb** [comment]
BTW: Is there a specific reason why you call ```GetMimeMessage``` instead of leaving this task to the ```Send``` method of ```MailMergeSender```, which also does the clean-up you're asking for?

**Comment by gary-palmer** [comment]
Ah yes, I am using the sender, but also using getMIMEmessage so i can serialize the message and provide a rough version of sent items (saved off after a successful send).

________________________________

**Comment by axunonb** [comment]
I see - it's always good to understand "what for". Well, you could easily save one or all messages to a directory using ```MailMergeSender.Send```. For that purpose just modify the ```SenderConfig/SmtpClientConfig``` as follows:
```csharp
MessageOutput = MessageOutput.Directory
MailOutputDirectory = @"C:\Which\Ever\Directory"
```
This feature may be a bit surprising in terms of "SMTP". I took it over from the MS mail system.
The clean-up you're asking for would come out-of-the-box.

You could prepare one ```SmtpClientConfig``` for the mail server, and another for writing to the file system. Then just apply them to ```MailMergeSender``` as needed.

**Comment by axunonb** [comment]
With the latest commit https://github.com/axuno/MailMergeLib/commit/68c80f79af1e2d30d3de2e9f653db2a3d91f7e98 there is new static method
```MailMergeMessage.DisposeFileStreams(theMimeMessage);```
that allows for closing open file streams after ```MailMergeMessage.GetMimeMessage()```.
This method is also called by ```MailMergeSender.Send()```
