### ISSUE TITLE
Error in GetMimeMessage

### ISSUE THREAD

**Issue by magomigo** [axuno/MailMergeLib#9]
Hi getting the mime message of an html like:
```
<html>
<head>
<script type="colorScheme" class="swatch active">
{"name":"Default","bgBody":"333333","link":"7E8564","color":"AAAAAA","bgIte=
m":"ffffff","title":"444444"}</script>
</head>
<body>
<p>Hello world!</p>
</body>
</html>
```
cause an index out of bound exception.
Exception occur in HtmlBodyBuilder.cs, method GetBodyPart().
By changing the following line:
`foreach (var element in _htmlDocument.All.Where(e => e is IHtmlScriptElement))`
in
```
var scriptsElements = _htmlDocument.All.Where(e => e is IHtmlScriptElement).ToList();
// remove all Script elements, because they cannot be used in mail messages
foreach (var element in scriptsElements)
```
everything works correctly.
Hope this could be helpful for next release.

**Comment by axunonb** [comment]
Yep, what a silly mistake. Thank you.
